export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  LOCKED_OUT: "LOCKED_OUT",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  DENIED: "DENIED",
  DISABLED: "DISABLED",
  REQUIRE_2FA: "REQUIRE_2FA",
  RESET_CODE_INVALID: "RESET_CODE_INVALID",
  RESET_CODE_EXPIRED: "RESET_CODE_EXPIRED",
  RESET_PASSWORD_INVALID: "RESET_PASSWORD_INVALID",
};

export class AuthError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "AuthError";
    this.code = code;
  }
}
