-- Station 101: Kunden address fields + mobile
ALTER TABLE kunden
  ADD COLUMN IF NOT EXISTS mobile VARCHAR(64) NOT NULL DEFAULT '' AFTER telefon,
  ADD COLUMN IF NOT EXISTS strasse VARCHAR(255) NOT NULL DEFAULT '' AFTER mobile,
  ADD COLUMN IF NOT EXISTS plz VARCHAR(32) NOT NULL DEFAULT '' AFTER strasse,
  ADD COLUMN IF NOT EXISTS ort VARCHAR(255) NOT NULL DEFAULT '' AFTER plz;
